/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sec_cwm_base_jni_newJni */

#ifndef _Included_com_sec_cwm_base_jni_newJni
#define _Included_com_sec_cwm_base_jni_newJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sec_cwm_base_jni_newJni
 * Method:    exec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sec_cwm_base_jni_newJni_exec
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
